# Generated by Django 4.1.7 on 2023-03-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('type', models.CharField(help_text='Тип оборудования', max_length=100, primary_key=True, serialize=False, verbose_name='тип')),
                ('description', models.CharField(help_text='Описание типа', max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(help_text='Id оборудования', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='Наименование оборудования', max_length=100, verbose_name='наименование')),
                ('short_desc', models.CharField(help_text='Краткое описание характеристик оборудования', max_length=200, verbose_name='краткое описание')),
                ('full_desc', models.CharField(help_text='Полное описание характеристик оборудования', max_length=1000, verbose_name='полное описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость оборудования', max_digits=11, verbose_name='стоимость')),
                ('pic', models.ImageField(default='default.png', height_field=800, help_text='Превью оборудования', upload_to='hardware', verbose_name='превью', width_field=1000)),
                ('type', models.ForeignKey(help_text='Тип оборудования', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaretype', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
