# Generated by Django 4.1.7 on 2023-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='pic',
            field=models.ImageField(default='default.png', help_text='Превью оборудования', upload_to='', verbose_name='превью'),
        ),
    ]
