# Generated by Django 4.1.7 on 2023-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(help_text='Логин пользователя', max_length=100, unique=True, verbose_name='login')),
                ('email', models.EmailField(help_text='E-mail пользователя', max_length=100, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(help_text='Телефонный номер пользователя', max_length=16, unique=True, verbose_name='phone_number')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет активен ли пользователь', verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет является ли пользователь персоналом', verbose_name='персонал')),
                ('is_superuser', models.BooleanField(default=False, help_text='Определяет является ли пользователь администратором', verbose_name='администратор')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
