# Generated by Django 4.1.7 on 2023-03-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('legal_name', models.CharField(max_length=100)),
                ('legal_address', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=100, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Определяет активен ли пользователь', verbose_name='статус активности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет является ли пользователь персоналом', verbose_name='статус персонала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Определяет является ли пользователь администратором', verbose_name='статус администратора'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(help_text='Логин пользователя', max_length=100, unique=True, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Телефонный номер пользователя', max_length=16, unique=True, verbose_name='номер телефона'),
        ),
    ]
