# Generated by Django 4.1.7 on 2023-03-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_manager_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legal_address',
            field=models.CharField(help_text='Юридический адрес клиента', max_length=100, verbose_name='юр. адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_name',
            field=models.CharField(help_text='Имя юридического лица клиента', max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_address',
            field=models.CharField(help_text='Почтовый адрес клиента', max_length=50, verbose_name='почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tin',
            field=models.CharField(help_text='ИНН клиента', max_length=10, unique=True, verbose_name='инн'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_id',
            field=models.OneToOneField(help_text='Id связанного пользователя клиента', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(help_text='Имя менеджера', max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='patronymic',
            field=models.CharField(help_text='Отчество менеджера', max_length=50, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='second_name',
            field=models.CharField(help_text='Фамилия менеджера', max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_id',
            field=models.OneToOneField(help_text='Id связанного пользователя менеджера', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
    ]
